zia/resource_zia_traffic_forwarding_static_ips.go, zia/resource_zia_traffic_forwarding_vpn_credentials.go
Updated schema with `ip_address` parameter with `ForceNew` so resource is recreated during updates
=> Updated schema with `ip_address` parameter with `ForceNew` so resource is recreated during updates

examples/zia_location_management/location_management_vpn_credentials.tf, examples/zia_traffic_forwarding_vpn_credentials/basic_ip_address.tf
Updated schema `type` parameter with `ForceNew` so resource is recreated if type attribute is changed
=> Updated schema `type` parameter with `ForceNew` so resource is recreated if type attribute is changed

GNUmakefile, gozscaler/trafficforwarding/vpncredentials/vpncredentials.go, zia/resource_zia_location_management.go, zia/resource_zia_traffic_forwarding_static_ips.go, zia/resource_zia_traffic_forwarding_vpn_credentials.go
=> Fix: required ip when location vpn creds type is IP & stop unnecessary resource updates

CHANGELOG.md, gozscaler/adminuserrolemgmt/adminusers.go, zia/resource_zia_admin_users.go, zia/resource_zia_dlp_dictionaries.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_fw_filtering_ip_destination_groups.go, zia/resource_zia_fw_filtering_ip_source_groups.go, zia/resource_zia_fw_filtering_network_application_groups.go, zia/resource_zia_fw_filtering_network_services.go, zia/resource_zia_fw_filtering_network_services_groups.go, zia/resource_zia_location_management.go, zia/resource_zia_url_categories.go, zia/resource_zia_url_filtering_rules.go, zia/resource_zia_user_management_users.go
Added support to import by name for ``terraform import`` PR #47
=> Added support to import by name for ``terraform import``

GNUmakefile, docs/data-sources/device_groups.md, docs/data-sources/devices.md, examples/zia_device_groups/datasource.tf, examples/zia_devices/datasource.tf, gozscaler/devicegroups/devicegroups.go, gozscaler/devicegroups/service.go, gozscaler/urlfilteringpolicies/urlfilteringpolicies.go, zia/config.go, zia/data_source_zia_device_group.go, zia/data_source_zia_devices.go, zia/data_source_zia_url_filtering_rules.go, zia/provider.go, zia/resource_zia_url_filtering_rules.go
feat: Added ``device_groups`` data source :rocket:
=> feat: Added ``device_groups`` data source :rocket:

GNUmakefile, docs/data-sources/device_groups.md, docs/data-sources/devices.md, examples/zia_device_groups/datasource.tf, examples/zia_devices/datasource.tf, gozscaler/common/common.go, gozscaler/devicegroups/devicegroups.go, gozscaler/devicegroups/service.go, gozscaler/urlfilteringpolicies/urlfilteringpolicies.go, zia/common.go, zia/config.go, zia/data_source_zia_device_group.go, zia/data_source_zia_devices.go, zia/data_source_zia_url_filtering_rules.go, zia/provider.go, zia/resource_zia_url_filtering_rules.go
feat: Added device_groups and devices to url_filtering_rules  🚀
=> feat: Added device_groups and devices to url_filtering_rules  🚀 

GNUmakefile, docs/data-sources/device_groups.md, docs/data-sources/devices.md, docs/data-sources/rule_labels.md, docs/resources/rule_labels.md, examples/zia_device_groups/datasource.tf, examples/zia_devices/datasource.tf, examples/zia_dlp_notification_templates/datasource.tf, examples/zia_rule_labels/basic.tf, examples/zia_rule_labels/datasource.tf, gozscaler/common/common.go, gozscaler/devicegroups/devicegroups.go, gozscaler/devicegroups/service.go, gozscaler/dlp_notification_templates/dlp_notification_templates.go, gozscaler/dlp_notification_templates/service.go, gozscaler/rule_labels/rule_labels.go, gozscaler/rule_labels/service.go, gozscaler/urlfilteringpolicies/urlfilteringpolicies.go, zia/common.go, zia/config.go, zia/data_source_zia_device_group.go, zia/data_source_zia_devices.go, zia/data_source_zia_dlp_notification_templates.go, zia/data_source_zia_rule_labels.go, zia/data_source_zia_url_filtering_rules.go, zia/provider.go, zia/resource_zia_dlp_notification_templates.go, zia/resource_zia_rule_labels.go, zia/resource_zia_url_filtering_rules.go
feat: Added new ``zia_rule_labels`` data_source and resource 🚀
=> feat: Added new ``zia_rule_labels`` data_source and resource 🚀 

.github/workflows/acceptance-tests.yml, cli/ziaActivator.go, docs/guide/zia_activator.md, docs/index.html.markdown, gozscaler/client/config.go, zia/config.go, zia/provider.go, zia/provider_test.go
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
=> Use zia cloud instead of zia base url

zia/data_source_zia_url_filtering_rules.go, zia/resource_zia_url_filtering_rules.go, zia/resource_zia_url_filtering_rules_test.go
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
=> Fix url filtering rule

zia/data_source_zia_user_management_users_test.go, zia/resource_zia_admin_users.go, zia/resource_zia_admin_users_test.go, zia/resource_zia_user_management_users.go, zia/resource_zia_user_management_users_test.go
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
=> fix users & admin users

zia/common/testing/variable/variable.go, zia/data_source_zia_firewall_filtering_rules_test.go, zia/resource_zia_firewall_filtering_rules_test.go
Added additional attributesets for zia_firewall_filtering_rules tests
=> Additional attributesets for zia_firewall_filtering_rules tests

zia/common/testing/variable/variable.go, zia/data_source_zia_location_management_test.go, zia/data_source_zia_traffic_forwarding_vpn_credentials_test.go, zia/resource_zia_dlp_dictionaries_test.go, zia/resource_zia_dlp_web_rules_test.go, zia/resource_zia_fw_filtering_ip_destination_groups_test.go, zia/resource_zia_fw_filtering_ip_source_groups_test.go, zia/resource_zia_fw_filtering_network_application_groups_test.go, zia/resource_zia_fw_filtering_network_services_groups_test.go, zia/resource_zia_fw_filtering_network_services_test.go, zia/resource_zia_location_management_test.go, zia/resource_zia_rule_labels_test.go, zia/resource_zia_traffic_forwarding_static_ips_test.go, zia/resource_zia_traffic_forwarding_vpn_credentials_test.go
Added: New Optimized Acceptance Tests
=> Added: New Optimized Acceptance Tests

CHANGELOG.md, GNUmakefile, docs/data-sources/zia_admin_roles.md, docs/data-sources/zia_auth_settings_urls.md, docs/resources/zia_auth_settings_urls.md, examples/zia_auth_settings_urls/datasource.tf, examples/zia_auth_settings_urls/main.tf, gozscaler/security_policy_settings/security_policy_settings.go, gozscaler/security_policy_settings/service.go, gozscaler/user_authentication_settings/service.go, gozscaler/user_authentication_settings/user_authentication_settings.go, zia/common/resourcetype/resource_type.go, zia/config.go, zia/data_source_security_policy_settings.go, zia/data_source_zia_auth_settings_urls.go, zia/data_source_zia_auth_settings_urls_test.go, zia/provider.go, zia/resource_zia_auth_settings_urls.go, zia/resource_zia_auth_settings_urls_test.go
New: Added User Authentication Settings
=> New: Added User Authentication Settings

GNUmakefile, gozscaler/client/config.go
=> fix http proxy use

cli/ziaActivator.go, docs/guides/zia_activator.md, gozscaler/client/client.go, gozscaler/client/config.go, zia/config.go, zia/provider.go
Added Terraform userAgent for backend API tracking
=> Added Terraform userAgent for backend API tracking

GNUmakefile, docs/resources/zia_traffic_forwarding_static_ip.md, docs/resources/zia_traffic_forwarding_vpn_credentials.md, gozscaler/trafficforwarding/vpncredentials/vpncredentials.go, zia/data_source_zia_traffic_forwarding_vpn_credentials.go, zia/resource_zia_traffic_forwarding_static_ips.go, zia/resource_zia_traffic_forwarding_vpn_credentials.go
Fix: Import static ip resource by IP
=> Fix: Import static ip resource by IP

zia/resource_zia_admin_users.go, zia/resource_zia_dlp_dictionaries.go, zia/resource_zia_dlp_notification_templates.go, zia/resource_zia_dlp_web_rules.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_fw_filtering_ip_destination_groups.go, zia/resource_zia_fw_filtering_ip_source_groups.go, zia/resource_zia_fw_filtering_network_application_groups.go, zia/resource_zia_fw_filtering_network_services.go, zia/resource_zia_fw_filtering_network_services_groups.go, zia/resource_zia_location_management.go, zia/resource_zia_rule_labels.go, zia/resource_zia_traffic_forwarding_static_ips.go, zia/resource_zia_traffic_forwarding_vpn_credentials.go, zia/resource_zia_url_categories.go, zia/resource_zia_url_filtering_rules.go, zia/resource_zia_user_management_users.go
This PR fixes resources import by ID
=> Fix resources import by ID

go.mod, go.sum
Updated to zscaler-sdk-go v0.1.1
=> Updated to zscaler-sdk-go v0.1.1

zia/data_source_zia_traffic_forwarding_static_ips.go, zia/resource_zia_traffic_forwarding_static_ips.go
Added missing parameter (Comment) to static_ip resource
=> (fix): Added missing parameter to static_ip resource

docs/guides/zia-activator-overview.md, docs/index.md, docs/resources/zia_activation_status.md
(fix):Updated Documentation for zia_activation
=> (fix):Updated Documentation for zia_activation

zia/resource_zia_activation.go
Added Customizable Timeouts to zia_activation
=> Added Customizable Timeouts to zia_activation

zia/common/resourcetype/resource_type.go, zia/common/testing/variable/variable.go, zia/data_source_zia_activation_status_test.go
Added zia_activation_status_test
=> Added zia_activation_status_test

GNUmakefile
Update broken GNUmakefile for ziaActivator
=> Update broken GNUmakefile for ziaActivator

CHANGELOG.md, GNUmakefile, go.mod, go.sum, zia/resource_zia_firewall_filtering_rules.go
=> Fix FW Enable Full Logging

zia/common.go, zia/resource_zia_dlp_web_rules.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_url_filtering_rules.go
This PR extract and uses common re-ordering logic for url & filtering rules
=> extract common reordering logic for url & filtering rules

zia/resource_zia_dlp_web_rules.go
(fix): Fix web dlp rule ocr validation
=> (fix): Fix web dlp rule ocr validation

CHANGELOG.md, docs/guides/release-notes.md, go.mod, go.sum, zia/common.go, zia/data_source_zia_user_management_users.go
(fix) User Management group flattening function
=> (fix) User Management group flattening function

CHANGELOG.md, docs/guides/release-notes.md, go.mod, go.sum, zia/data_source_zia_location_management.go, zia/resource_zia_location_management.go
(feat) Add support to sublocation search function
=> (feat) Add support to sublocation search function

go.mod, go.sum, zia/data_source_zia_traffic_forwarding_gre_vip_recommended_list.go, zia/resource_zia_traffic_forwarding_gre_tunnels.go
(fix) Traffic Forwarding GRE Tunnel Error
=> (fix) Traffic Forwarding GRE Tunnel Error

CHANGELOG.md, docs/guides/release-notes.md, go.mod, go.sum, zia/data_source_zia_dlp_engines.go, zia/data_source_zia_dlp_engines_test.go
(fix) DLP Engine Resource SearchByName
=> (fix) DLP Engine Resource SearchByName

CHANGELOG.md, docs/guides/release-notes.md, go.mod, go.sum
(Fix)Updated to zscaler-sdk-go v1.4.0
=> (Fix)Updated to zscaler-sdk-go v1.4.0

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/resources/zia_dlp_web_rules.md, examples/zia_dlp_web_rules/basic.tf, zia/common.go, zia/data_source_zia_dlp_web_rules.go
(Fix)Reduced NewTicker timer for faster rule processing
=> (Fix)Reduced NewTicker timer for faster rule processing

CHANGELOG.md, docs/data-sources/zia_sub_location_management.md, docs/guides/release-notes.md, examples/zia_sub_location_management/datasource.tf, zia/data_source_zia_location_management.go
data "zia_location_management" "usa_sjc37" {
name = "USA-SJC37"
parent_name = "USA"
}
=> Fetch specific sub-location of a location by name

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, go.mod, go.sum, zia/config.go, zia/data_source_zia_dlp_edm_schema.go, zia/provider.go
(feat) Added DLP Exact Data Match Datasource
=> (feat) Added DLP Exact Data Match Datasource

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, zia/resource_zia_user_management_users.go
=> feat:re-enroll user on password update

CHANGELOG.md, docs/guides/release-notes.md, zia/resource_zia_url_filtering_rules.go
Fix: Fixed order drift within url_filtering_rule
=> Fix: Fixed order drift within url_filtering_rule

.github/workflows/reuse-zia-tests.yml, .github/workflows/test.yml, GNUmakefile, go.mod, go.sum, zia/common.go, zia/common/resourcetype/resource_type.go, zia/common/testing/variable/variable.go, zia/data_source_zia_dlp_web_rules.go, zia/data_source_zia_dlp_web_rules_test.go, zia/data_source_zia_firewall_filtering_rules.go, zia/data_source_zia_firewall_filtering_rules_test.go, zia/data_source_zia_url_filtering_rules.go, zia/data_source_zia_url_filtering_rules_test.go, zia/provider_sweeper_test.go, zia/provider_test.go, zia/resource_zia_admin_users_test.go, zia/resource_zia_dlp_web_rules_test.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_firewall_filtering_rules_test.go, zia/resource_zia_location_management_test.go, zia/resource_zia_traffic_forwarding_static_ips_test.go, zia/resource_zia_traffic_forwarding_vpn_credentials_test.go, zia/resource_zia_url_filtering_rules.go, zia/resource_zia_url_filtering_rules_test.go, zia/resource_zia_user_management_users_test.go, zia/utils_for_test.go
(gh-action): Implement retry workflow method
=> (gh-action): Implement retry workflow method

CHANGELOG.md, docs/guides/release-notes.md, docs/guides/troubleshooting.md, docs/resources/zia_firewall_filtering_network_service.md
(doc) Updated network service documentation
=> (doc) Updated network service documentation

CHANGELOG.md, README.md, docs/guides/resource-importer.md, docs/index.md
(doc) Fixed index page links to support statement
=> (doc) Fixed index page links to support statement

.github/workflows/test.yml, go.mod, go.sum, zia/resource_zia_location_management.go
Fix: Upgrade to zscaler-sdk-go v2.1.4
=> Fix: Upgrade to zscaler-sdk-go v2.1.4

.github/workflows/test.yml, CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/resources/zia_location_management.md, zia/common/testing/variable/variable.go, zia/resource_zia_admin_users_test.go, zia/resource_zia_location_management.go, zia/resource_zia_traffic_forwarding_vpn_credentials_test.go, zia/resource_zia_user_management_users_test.go
fix: Location Management ip_adddress `TypeSet`
=> fix: Location Management ip_adddress

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_firewall_filtering_rules_test.go
(Fix): Fixes firewall rule dest_countries drift
=> (Fix): Fixes firewall rule dest_countries drift

GNUmakefile, zia/common.go, zia/resource_zia_activation_test.go, zia/resource_zia_dlp_web_rules.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_firewall_filtering_rules_test.go, zia/resource_zia_url_filtering_rules.go, zia/utils_for_test.go, zia/validator.go
(Fix) Implemented linter for S019
=> (Fix) Implemented linter for S019

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/resources/zia_admin_users.md, examples/zia_admin_user/admin_user_department_scope.tf, examples/zia_admin_user/admin_user_location_group_scope.tf, examples/zia_admin_user/admin_user_location_scope.tf, examples/zia_admin_user/admin_user_organization_scope.tf, zia/resource_zia_admin_users.go, zia/resource_zia_admin_users_test.go, zia/version.go
fix: Fixed  resource due to function panic and API changes
=> fix: Fixed  resource due to function panic and API changes

CHANGELOG.md, docs/guides/release-notes.md, go.mod, go.sum, zia/common.go, zia/data_source_zia_activation_status_test.go, zia/data_source_zia_dlp_web_rules_test.go, zia/data_source_zia_firewall_filtering_rules.go, zia/data_source_zia_firewall_filtering_rules_test.go, zia/data_source_zia_forwarding_control_rule.go, zia/resource_zia_activation_test.go, zia/resource_zia_dlp_web_rules_test.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_firewall_filtering_rules_test.go, zia/resource_zia_forwarding_control_rule.go, zia/resource_zia_url_filtering_rules_test.go, zia/validator.go
(feat): Added support to zpa application segment in cloud firewall resource
=> (feat): Added support to zpa application segment

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, go.mod, go.sum, zia/common.go, zia/config.go, zia/data_source_zia_sandbox_report_test.go, zia/data_source_zia_workload_groups.go, zia/provider.go
feat: Added Support for Workload Groups Tagging
=> feat: Added Support for Workload Groups Tagging

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, zia/GNUmakefile, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_forwarding_control_rule.go, zia/resource_zia_forwarding_control_zpa_gateway.go, zia/resource_zia_fw_filtering_ip_destination_groups.go
fix: Added validation to several resources
=> fix: Added validation to several resources

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, go.mod, go.sum, zia/resource_zia_traffic_forwarding_vpn_credentials.go
Fixed VPN Credential Importing ID Issue
=> Fixed VPN Credential Importing ID Issue

.github/workflows/zia-test.yml, CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/resources/zia_dlp_web_rules.md, go.mod, go.sum, zia/data_source_zia_admin_roles.go, zia/data_source_zia_application_services_group_lite.go, zia/data_source_zia_application_services_lite.go, zia/data_source_zia_cloud_browser_isolation_profile.go, zia/data_source_zia_device_group.go, zia/data_source_zia_dlp_web_rules.go, zia/data_source_zia_fw_filtering_time_window.go, zia/resource_zia_dlp_web_rules.go
fix: Fixed zia_dlp_web_rules new parent_rule and sub_rules attributes
=> fix: Fixed zia_dlp_web_rules new parent_rule and sub_rules attributes

go.mod, go.sum, zia/resource_zia_dlp_web_rules.go, zia/resource_zia_location_management.go, zia/resource_zia_url_filtering_rules.go
fix: Fixed computed attributes in the schema
=> fix: Fixed computed attributes in the schema

.github/workflows/zia-test.yml, CHANGELOG.md, GNUmakefile, README.md, docs/guides/release-notes.md, docs/resources/zia_location_management.md, docs/resources/zia_url_filtering_rules.md, go.mod, go.sum, zia/common/version.go, zia/resource_zia_location_management.go, zia/resource_zia_url_filtering_rules.go, zia/version.go
Fixed ``zia_url_filtering_rules`` schema validation
=> Fixed ``zia_url_filtering_rules`` schema validation

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, go.mod, go.sum, zia/common.go, zia/data_source_zia_ssl_inspection_rules.go, zia/resource_zia_advanced_settings.go, zia/resource_zia_ssl_inspection_rules.go
=> fix: Fixed SSL Inspection panic

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, zia/resource_zia_dlp_notification_templates.go, zia/resource_zia_end_user_notification.go, zia/resource_zia_end_user_notification_test.go, zia/resource_zia_forwarding_control_zpa_gateway.go, zia/utils.go, zia/validator.go
=> fix: Fixed Validation Issues with End User Notification Resource

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/resources/zia_firewall_dns_rules.md, docs/resources/zia_firewall_filtering_rule.md, docs/resources/zia_ssl_inspection_rules.md, zia/common.go, zia/data_source_zia_url_filtering_and_cloud_app_settings_test.go, zia/provider_test.go, zia/resource_zia_atp_malware_settings_test.go, zia/resource_zia_cloud_app_control_rules_test.go, zia/resource_zia_firewall_dns_rules.go, zia/resource_zia_firewall_dns_rules_test.go, zia/resource_zia_firewall_filtering_rules.go, zia/resource_zia_firewall_filtering_rules_test.go, zia/resource_zia_firewall_ips_rules.go, zia/resource_zia_sandbox_submission_test.go, zia/resource_zia_ssl_inspection_rules_test.go, zia/resource_zia_url_filtering_and_cloud_app_settings_test.go
=> Fix: Improved the rule reorder logic

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, go.mod, go.sum, zia/config.go, zia/provider_test.go, zia/resource_zia_auth_settings_urls.go, zia/resource_zia_sandbox_behavioral_analysis_advanced_settings.go, zia/resource_zia_security_policy_settings.go, zia/resource_zia_url_filtering_rules.go, zia/validator.go
=> fix: Fixed resources with custom IDs

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, zia/resource_zia_firewall_dns_rules.go, zia/resource_zia_sandbox_rules.go, zia/resource_zia_ssl_inspection_rules.go
=> fix: Fixed SSL Inspection Rules panic

CHANGELOG.md, GNUmakefile, docs/guides/release-notes.md, docs/index.md, zia/common/version.go, zia/validator.go
=> fix: Fixed Cloud App Control Rule Validation

CHANGELOG.md, docs/guides/release-notes.md, docs/resources/zia_activation_status.md, zia/resource_zia_firewall_filtering_rules.go
=> fix: Fixed Firewall Rules Description Heredoc handling
